force-app/main/default/objects/Case/fields/Asset_Type__c.field-meta.xml
<CustomField>
    <fullName>Asset_Type__c</fullName>
    <label>Asset Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Car</fullName>
            </value>
            <value>
                <fullName>Motorbike</fullName>
            </value>
            <value>
                <fullName>Caravan</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Business_ABN__c.field-meta.xml
<CustomField>
    <fullName>Business_ABN__c</fullName>
    <label>Business ABN</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Duration__c.field-meta.xml
<CustomField>
    <fullName>Business_Duration__c</fullName>
    <label>Business Duration</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Business_GST__c.field-meta.xml
<CustomField>
    <fullName>Business_GST__c</fullName>
    <label>Business GST</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Buying_a_Car_From__c.field-meta.xml
<CustomField>
    <fullName>Buying_a_Car_From__c</fullName>
    <label>Buying a Car From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dealership</fullName>
            </value>
            <value>
                <fullName>Private sale</fullName>
            </value>
            <value>
                <fullName>Still deciding</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
                <isActive>false</isActive>
                <label>Private</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Cash_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Cash_Deposit__c</fullName>
    <label>Cash Deposit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Currently_on_Probation__c.field-meta.xml
<CustomField>
    <fullName>Currently_on_Probation__c</fullName>
    <label>Currently On Probation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Deposit__c.field-meta.xml
<CustomField>
    <fullName>Deposit__c</fullName>
    <label>Deposit</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Driva_UUID__c.field-meta.xml
<CustomField>
    <fullName>Driva_UUID__c</fullName>
    <label>Driva UUID</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Employment_Status__c.field-meta.xml
<CustomField>
    <fullName>Employment_Status__c</fullName>
    <formula>TEXT (Contact.Employment_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employment Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Angle</fullName>
            </value>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>BFS</fullName>
            </value>
            <value>
                <fullName>Finance One</fullName>
            </value>
            <value>
                <fullName>GetCapital</fullName>
            </value>
            <value>
                <fullName>Grow</fullName>
            </value>
            <value>
                <fullName>Latitude</fullName>
            </value>
            <value>
                <fullName>Liberty</fullName>
            </value>
            <value>
                <fullName>Macquarie</fullName>
            </value>
            <value>
                <fullName>Metro</fullName>
            </value>
            <value>
                <fullName>Money3</fullName>
            </value>
            <value>
                <fullName>MoneyPlace</fullName>
            </value>
            <value>
                <fullName>Now Finance</fullName>
            </value>
            <value>
                <fullName>Pepper</fullName>
            </value>
            <value>
                <fullName>Society One</fullName>
            </value>
            <value>
                <fullName>Afs</fullName>
            </value>
            <value>
                <fullName>Finance One Commercial</fullName>
            </value>
            <value>
                <fullName>Liberty Commercial</fullName>
            </value>
            <value>
                <fullName>Macquarie Commercial</fullName>
            </value>
            <value>
                <fullName>Pepper Commercial</fullName>
            </value>
            <value>
                <fullName>Prospa</fullName>
            </value>
            <value>
                <fullName>Plenti PL</fullName>
            </value>
            <value>
                <fullName>SocietyOne</fullName>
            </value>
            <value>
                <fullName>St.George</fullName>
            </value>
            <value>
                <fullName>Westpac</fullName>
            </value>
            <value>
                <fullName>Wisr PL</fullName>
            </value>
            <value>
                <fullName>Plenti Commercial</fullName>
            </value>
            <value>
                <fullName>Firstmac</fullName>
            </value>
            <value>
                <fullName>Plenti</fullName>
            </value>
            <value>
                <fullName>Wisr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Loan_Class__c.field-meta.xml
<CustomField>
    <fullName>Loan_Class__c</fullName>
    <label>Loan Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term__c</fullName>
    <label>Loan Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type__c</fullName>
    <label>Loan Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Refinance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Previous_Employment_Duration_Months__c.field-meta.xml
<CustomField>
    <fullName>Previous_Employment_Duration_Months__c</fullName>
    <label>Previous Employment Duration Months</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Previous_Employment_Duration_Years__c.field-meta.xml
<CustomField>
    <fullName>Previous_Employment_Duration_Years__c</fullName>
    <label>Previous Employment Duration Years</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Time_in_Current_Employment_Months__c.field-meta.xml
<CustomField>
    <fullName>Time_in_Current_Employment_Months__c</fullName>
    <label>Time in Current Employment Months</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Time_in_Current_Employment_Years__c.field-meta.xml
<CustomField>
    <fullName>Time_in_Current_Employment_Years__c</fullName>
    <label>Time in Current Employment Years</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Total_deposit_calculated__c.field-meta.xml
<CustomField>
    <fullName>Total_deposit_calculated__c</fullName>
    <formula>Cash_Deposit__c + ( Trade_in_Value__c -  Trade_in_Finance_owing__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total deposit (calculated)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Trade_in_Finance_owing__c.field-meta.xml
<CustomField>
    <fullName>Trade_in_Finance_owing__c</fullName>
    <description>The amount of finance-owed on the vehicle being traded-in.</description>
    <label>Trade-in Finance-owing</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Trade_in_Value__c.field-meta.xml
<CustomField>
    <fullName>Trade_in_Value__c</fullName>
    <description>The trade-in vehicle value</description>
    <label>Trade-in Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Vehicle_Price__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Price__c</fullName>
    <label>Vehicle Price</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Vehicle_year__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_year__c</fullName>
    <label>Vehicle Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Employment_Status__c.field-meta.xml
<CustomField>
    <fullName>Employment_Status__c</fullName>
    <label>Employment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Time</fullName>
            </value>
            <value>
                <fullName>Part Time</fullName>
            </value>
            <value>
                <fullName>Self Employed</fullName>
            </value>
            <value>
                <fullName>Casual</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Unemployed</fullName>
            </value>
            <value>
                <fullName>Pension</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Living_situation__c.field-meta.xml
<CustomField>
    <fullName>Living_situation__c</fullName>
    <label>Living Situation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Renting</fullName>
            </value>
            <value>
                <fullName>Renting But Own Property</fullName>
            </value>
            <value>
                <fullName>Owner With Mortgage</fullName>
            </value>
            <value>
                <fullName>Owner Without Mortgage</fullName>
            </value>
            <value>
                <fullName>Living With Parents</fullName>
            </value>
            <value>
                <fullName>Board</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Residency_Status__c.field-meta.xml
<CustomField>
    <fullName>Residency_Status__c</fullName>
    <label>Residency Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Permanent resident</fullName>
            </value>
            <value>
                <fullName>Australian citizen</fullName>
            </value>
            <value>
                <fullName>Temporary Visa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LoanDetailController.cls
/*************************** 
* @Name         LoanDetailController 
* @Author       vasu@driva.com.au
* @Date         22/06/2022
* @description  Handles Loan Recalculations, Calculate pricing and Retrieving Scores
******************************************************
/* MODIFICATION LOG
* Version          Developer          Date               Description
*-----------------------------------------------------------------------
*  1.0              Vasu      22/06/2022          Initial Creation 

****************************** */
public with sharing class LoanDetailController {
    @TestVisible
    private static String continuationLabel;
    @TestVisible
    private static String continuationState;
    @AuraEnabled(Cacheable = true)
    public static Case getCaseDetails(String recordId){
        return [Select Id, Lender__c,
                Vehicle_Price__c,
                Deposit__c,
                Loan_Term__c,
                Loan_Type__c,
                Loan_Class__c,
                Asset_Type__c,
                Employment_Status__c,
                Contact.Residency_Status__c,
                Time_in_Current_Employment_Years__c,
                Time_in_Current_Employment_Months__c,
                Previous_Employment_Duration_Years__c,
                Previous_Employment_Duration_Months__c,
                Currently_on_Probation__c,
                Business_Duration__c,
                Business_ABN__c,
                Business_GST__c,
                Contact.Living_situation__c,
                Contact.Email,
                Buying_a_Car_From__c,
                Vehicle_year__c, Driva_UUID__c, Status,Trade_in_Value__c,Cash_Deposit__c,Trade_in_Finance_owing__c,Total_deposit_calculated__c From Case Where Id =: recordId limit 1];
    }
    
    @AuraEnabled(continuation=true cacheable=true)
    //public static Object recalculateAPI(String payload, String UUID) {
   public static Object recalculateAPI(String payload) {
         //String url = System.Label.recalculateAPIUrl + UUID;
       String url = System.Label.recalculateAPIUrl;
        String jwtToken = JWT.sign();
        Continuation con = new Continuation(40);
        // Set callback method
        con.continuationMethod = 'processResponse';
        // Create callout request
        HttpRequest req = new HttpRequest();
        req.setEndpoint(url);
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json;charset=UTF-8');
        system.debug('===jwtToken  ==> ' + jwtToken);
        system.debug('===body request ==> ' + payload);
        req.setBody(payload);
        req.setHeader('Authorization', 'Bearer ' + jwtToken);
        // Add callout request to continuation
        if(Test.isRunningTest()){
            continuationLabel = con.addHttpRequest(req);
            continuationState = con.addHttpRequest(req);
            con.state = continuationState;
        }else{
            con.addHttpRequest(req);
        }
        // Return the continuation
        return con;
    }
    //Start- Retrieve new scores and calculate pricing -Agent 2207 
    //calling the calculate price API
    @AuraEnabled(continuation=true cacheable=true)
    public static Object calculatePricingAPI(String payload){
        System.debug(payload);
        String url = System.Label.calculatePricingAPIUrl;
        String jwtToken = JWT.sign();
        Continuation con = new Continuation(40);
        // Set callback method
        con.continuationMethod = 'processResponse';
        // Create callout request
        HttpRequest req = new HttpRequest();
        req.setEndpoint(url);
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json;charset=UTF-8');
        system.debug('===jwtToken  ==> ' + jwtToken);
        system.debug('===body request ==> ' + payload);
        req.setBody(payload);
        req.setHeader('Authorization', 'Bearer ' + jwtToken);
        if(Test.isRunningTest()){
            continuationLabel = con.addHttpRequest(req);
            continuationState = con.addHttpRequest(req);
            con.state = continuationState;
        }else{
            con.addHttpRequest(req);
        }
        // Return the continuation
        return con;
        
    }
    //calling the retrieve score API 
    @AuraEnabled(continuation = true cacheable = true)
    public static Object retrieveScoreAPI(String UUID){
        String url = System.Label.retrieveScoreAPIUrl + UUID ;
        System.debug('URL==>'+url);
        String jwtToken = JWT.sign();
        Continuation con = new Continuation(40);
        // Set callback method
        con.continuationMethod = 'processResponse';
        // Create callout request
        HttpRequest req = new HttpRequest();
        req.setEndpoint(url);
        req.setMethod('GET');
        req.setHeader('Authorization', 'Bearer ' + jwtToken);
        if(Test.isRunningTest()){
            continuationLabel = con.addHttpRequest(req);
            continuationState = con.addHttpRequest(req);
            con.state = continuationState;
        }else{
            con.addHttpRequest(req);
        }
        // Return the continuation
        return con;
    }
     //End- Retrieve new scores and calculate pricing -Agent 2207 
     
   
    
    // Callback method
    @AuraEnabled
    public static Object processResponse(List<String> labels, Object state) {
        // Get the response by using the unique label
        HttpResponse response = Continuation.getResponse(labels[0]);
        system.debug('res => ' + response.getBody());
        // Set the result variable
        if(response != null) {
            if(response.getBody() != null) {
                return response.getBody();  
            }
        }
        return 'error';
    }
    @AuraEnabled
    public static string updateRecord(Case record){
        System.debug('case record => ' + record);
        try {
            update record;
            return 'Success';
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static Boolean checkValidCaseStatus(String recordId){
        Set<String> caseStatus = new Set<String>{'Quoted','Started','Awaiting Documents','Under Review','Lodged','Conditionally Approved','Approved','Settled','Withdrawn','Declined','Referred','Closed - No Contact'};
        List<Case> cases = [Select Id, Status From Case Where Id =: recordId AND Status IN :caseStatus limit 1];
        if(cases.size() > 0){
            return true;
        }else{
            return false;
        }
    }
}