force-app/main/default/objects/Case/fields/Asset_Type__c.field-meta.xml
<CustomField>
    <fullName>Asset_Type__c</fullName>
    <label>Asset Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Car</fullName>
            </value>
            <value>
                <fullName>Motorbike</fullName>
            </value>
            <value>
                <fullName>Caravan</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Business_ABN__c.field-meta.xml
<CustomField>
    <fullName>Business_ABN__c</fullName>
    <label>Business ABN</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Duration__c.field-meta.xml
<CustomField>
    <fullName>Business_Duration__c</fullName>
    <label>Business Duration</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Business_GST__c.field-meta.xml
<CustomField>
    <fullName>Business_GST__c</fullName>
    <label>Business GST</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Buying_a_Car_From__c.field-meta.xml
<CustomField>
    <fullName>Buying_a_Car_From__c</fullName>
    <label>Buying a Car From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dealership</fullName>
            </value>
            <value>
                <fullName>Private sale</fullName>
            </value>
            <value>
                <fullName>Still deciding</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
                <isActive>false</isActive>
                <label>Private</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Deposit__c.field-meta.xml
<CustomField>
    <fullName>Deposit__c</fullName>
    <label>Deposit</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Driva_UUID__c.field-meta.xml
<CustomField>
    <fullName>Driva_UUID__c</fullName>
    <label>Driva UUID</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Employment_Industry_Continuation__c.field-meta.xml
<CustomField>
    <fullName>Employment_Industry_Continuation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Employment Industry Continuation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Employment_Status__c.field-meta.xml
<CustomField>
    <fullName>Employment_Status__c</fullName>
    <formula>TEXT (Contact.Employment_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employment Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Angle</fullName>
            </value>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>BFS</fullName>
            </value>
            <value>
                <fullName>Finance One</fullName>
            </value>
            <value>
                <fullName>GetCapital</fullName>
            </value>
            <value>
                <fullName>Grow</fullName>
            </value>
            <value>
                <fullName>Latitude</fullName>
            </value>
            <value>
                <fullName>Liberty</fullName>
            </value>
            <value>
                <fullName>Macquarie</fullName>
            </value>
            <value>
                <fullName>Metro</fullName>
            </value>
            <value>
                <fullName>Money3</fullName>
            </value>
            <value>
                <fullName>MoneyPlace</fullName>
            </value>
            <value>
                <fullName>Now Finance</fullName>
            </value>
            <value>
                <fullName>Pepper</fullName>
            </value>
            <value>
                <fullName>Society One</fullName>
            </value>
            <value>
                <fullName>Afs</fullName>
            </value>
            <value>
                <fullName>Finance One Commercial</fullName>
            </value>
            <value>
                <fullName>Liberty Commercial</fullName>
            </value>
            <value>
                <fullName>Macquarie Commercial</fullName>
            </value>
            <value>
                <fullName>Pepper Commercial</fullName>
            </value>
            <value>
                <fullName>Prospa</fullName>
            </value>
            <value>
                <fullName>Plenti PL</fullName>
            </value>
            <value>
                <fullName>SocietyOne</fullName>
            </value>
            <value>
                <fullName>St.George</fullName>
            </value>
            <value>
                <fullName>Westpac</fullName>
            </value>
            <value>
                <fullName>Wisr PL</fullName>
            </value>
            <value>
                <fullName>Plenti Commercial</fullName>
            </value>
            <value>
                <fullName>Firstmac</fullName>
            </value>
            <value>
                <fullName>Plenti</fullName>
            </value>
            <value>
                <fullName>Wisr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Loan_Class__c.field-meta.xml
<CustomField>
    <fullName>Loan_Class__c</fullName>
    <label>Loan Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term__c</fullName>
    <label>Loan Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type__c</fullName>
    <label>Loan Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Refinance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Previous_Employment_Duration_Months__c.field-meta.xml
<CustomField>
    <fullName>Previous_Employment_Duration_Months__c</fullName>
    <label>Previous Employment Duration Months</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Previous_Employment_Duration_Years__c.field-meta.xml
<CustomField>
    <fullName>Previous_Employment_Duration_Years__c</fullName>
    <label>Previous Employment Duration Years</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Time_in_Current_Employment_Months__c.field-meta.xml
<CustomField>
    <fullName>Time_in_Current_Employment_Months__c</fullName>
    <label>Time in Current Employment Months</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Time_in_Current_Employment_Years__c.field-meta.xml
<CustomField>
    <fullName>Time_in_Current_Employment_Years__c</fullName>
    <label>Time in Current Employment Years</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Vehicle_Price__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Price__c</fullName>
    <label>Vehicle Price</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Vehicle_year__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_year__c</fullName>
    <label>Vehicle Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LoanDetailControllerTest.cls
/*************************** 
* @Name         LoanDetailControllerTest 
* @Author       vasu@driva.com.au
* @Date         22/06/2022
* @description  Test class for  Loan Recalculations, Calculate pricing and Retrieving Scores
******************************************************
/* MODIFICATION LOG
* Version          Developer          Date               Description
*-----------------------------------------------------------------------
*  1.0              Vasu      22/06/2022          Initial Creation 

****************************** */
@isTest
public class LoanDetailControllerTest {
    
    private static case createCaseRecord(){
        Case objcase = new Case();
        objcase.Status = 'Received';
        objcase.Origin = 'Phone';
        return objcase;
    }
	@isTest
    public static void getCaseDetailsUpdateRecordTest() {
        Case objcase = createCaseRecord();
        insert objcase;
        System.assert(objcase.Id != null);
        LoanDetailController.getCaseDetails(objcase.Id);
        objcase.Deposit__c = 400;
        LoanDetailController.updateRecord(objcase);
        System.assert(objcase.Deposit__c == 400);
        Boolean isValid = LoanDetailController.checkValidCaseStatus(objcase.Id);
        System.assert(isValid == false);
    }
    
    
    
    @isTest
    public static void recalculateAPITest(){
        
        String jsonString = '{"Driva_UUID__c":"2057dd86-77dc-4db7-a9fa-d1fec0fcabaa","Lender__c":"Firstmac","Vehicle_Price__c":28274,"Deposit__c":6000,"Loan_Term__c":"5","Loan_Type__c":"Purchase","Loan_Class__c":"Consumer","Asset_Type__c":"Car","Time_in_Current_Employment_Years__c":19,"Employment_Status__c":null,"Time_in_Current_Employment_Months__c":1,"Previous_Employment_Duration_Years__c":null,"Previous_Employment_Duration_Months__c":null,"Employment_Industry_Continuation__c":false,"Business_Duration__c":null,"Business_ABN__c":null,"Business_GST__c":null,"Living_situation__c":null,"Residency_Status__c":"Permanent resident","Buying_a_Car_From__c":"Dealership","Vehicle_year__c":"2017"}';
        Test.startTest();
        	LoanDetailController.recalculateAPI(jsonString);
        Test.stopTest();
		// Create a mock response
        HttpResponse response = new HttpResponse();
        response.setStatusCode(200);
        response.setBody('{"success":true,"data":{"publicId":"OlTG1D1duY","displayName":"Firstmac","isEligible":true,"isPublic":true,"monthlyFees":0,"brokerageFee":990,"interestRate":7.39,"originationFee":400,"balloonPayment":0,"monthly":473,"comparisonRate":9.36,"realComparisonRate":10.08,"term":5,"terminationFees":"$700 in year 1, then $500 (None in final year","keyFeature":"Great for first time borrowers","isSecured":1,"meta":{"logo":"https://jump-marketing-assets.s3-ap-southeast-2.amazonaws.com/driva-email/firstmacLogo.png","terminationFeesAmount":"$700 in year 1, then $500 (None in final year"},"optionId":8}}');
        Test.setContinuationResponse(LoanDetailController.continuationLabel, response);
        List<String> labels = new List<String>{LoanDetailController.continuationLabel};
		String result = (String)LoanDetailController.processResponse(labels, LoanDetailController.continuationState);
        System.assert(result == '{"success":true,"data":{"publicId":"OlTG1D1duY","displayName":"Firstmac","isEligible":true,"isPublic":true,"monthlyFees":0,"brokerageFee":990,"interestRate":7.39,"originationFee":400,"balloonPayment":0,"monthly":473,"comparisonRate":9.36,"realComparisonRate":10.08,"term":5,"terminationFees":"$700 in year 1, then $500 (None in final year","keyFeature":"Great for first time borrowers","isSecured":1,"meta":{"logo":"https://jump-marketing-assets.s3-ap-southeast-2.amazonaws.com/driva-email/firstmacLogo.png","terminationFeesAmount":"$700 in year 1, then $500 (None in final year"},"optionId":8}}');
		
    }
    @isTest 
    public static void calculatePricingAPITest(){
        String jsonString = '{"loanUuid":"2057dd86-77dc-4db7-a9fa-d1fec0fcabaa","email":"testcontact@yopmail.com"}';
        Test.startTest();
           LoanDetailController.calculatePricingAPI(jsonString); 
        Test.stopTest();
        // Create a mock response
        HttpResponse response = new HttpResponse();
        response.setStatusCode(200);
        response.setBody('{"success":true,"data":{"publicId":"OlTG1D1duY","displayName":"Firstmac","isEligible":true,"isPublic":true,"monthlyFees":0,"brokerageFee":990,"interestRate":7.39,"originationFee":400,"balloonPayment":0,"monthly":473,"comparisonRate":9.36,"realComparisonRate":10.08,"term":5,"terminationFees":"$700 in year 1, then $500 (None in final year","keyFeature":"Great for first time borrowers","isSecured":1,"meta":{"logo":"https://jump-marketing-assets.s3-ap-southeast-2.amazonaws.com/driva-email/firstmacLogo.png","terminationFeesAmount":"$700 in year 1, then $500 (None in final year"},"optionId":8}}');
        Test.setContinuationResponse(LoanDetailController.continuationLabel, response);
        List<String> labels = new List<String>{LoanDetailController.continuationLabel};
		String result = (String)LoanDetailController.processResponse(labels, LoanDetailController.continuationState);
        System.assert(result == '{"success":true,"data":{"publicId":"OlTG1D1duY","displayName":"Firstmac","isEligible":true,"isPublic":true,"monthlyFees":0,"brokerageFee":990,"interestRate":7.39,"originationFee":400,"balloonPayment":0,"monthly":473,"comparisonRate":9.36,"realComparisonRate":10.08,"term":5,"terminationFees":"$700 in year 1, then $500 (None in final year","keyFeature":"Great for first time borrowers","isSecured":1,"meta":{"logo":"https://jump-marketing-assets.s3-ap-southeast-2.amazonaws.com/driva-email/firstmacLogo.png","terminationFeesAmount":"$700 in year 1, then $500 (None in final year"},"optionId":8}}');
        
    }
    @isTest
    public static void retrieveScoreAPITest(){
        String UUID = '2057dd86-77dc-4db7-a9fa-d1fec0fcabaa';
        Test.startTest();
        LoanDetailController.retrieveScoreAPI(UUID); 
        Test.stopTest();
    }
}