force-app/main/default/objects/Case/fields/Assessment_Quality__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Quality__c</fullName>
    <label>Assessment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Be Assessed</fullName>
            </value>
            <value>
                <fullName>At Verification</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Urgent</fullName>
            </value>
            <value>
                <fullName>Ready To Lodge</fullName>
            </value>
            <value>
                <fullName>Lodged</fullName>
            </value>
            <value>
                <fullName>Conditionally Approved</fullName>
            </value>
            <value>
                <fullName>-</fullName>
                <isActive>false</isActive>
                <label>-</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Need_To_Notify_Customer__c.field-meta.xml
<CustomField>
    <fullName>Need_To_Notify_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Need To Notify Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Under_Review_Date__c.field-meta.xml
<CustomField>
    <fullName>Under_Review_Date__c</fullName>
    <description>Changing Field Type from Date to Date/Time</description>
    <label>Under Review Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/SendEmailSMSAlertsBatch.cls
public class SendEmailSMSAlertsBatch implements Database.Batchable<sObject> {
    public Date currDate;
    public SendEmailSMSAlertsBatch(Date currentDate){
        currDate = currentDate;
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC){      
        return Database.getQueryLocator('SELECT Id,ContactEmail,ContactId,Need_To_Notify_Customer__c from Case where (Status = \'Under Review\' AND Assessment_Quality__c = \'To Be Assessed\' AND ContactId != NULL) AND (Under_Review_Date__c = YESTERDAY OR Need_To_Notify_Customer__c = True)');
    }
    
    public void execute(Database.BatchableContext BC, List<Case> scope){
        system.debug('scope+==> '+scope);
        //Date currDate = System.today();
        BusinessHours bHours;
        bHours = [SELECT Id FROM BusinessHours WHERE Name = 'Driva'];
        if(BusinessHours.isWithin(bHours.Id, currDate)){
            SendEmailSMSAlertsBatchHelper.sendEmailAndSMS(scope);
        }
        else{
            //update the notify customer field as true as customer will be alerted the next business day
            List<Case> updateCases = new List<Case>();
            for(Case caseObj : scope){
                Case caseRec = new Case(Id = caseObj.Id);
                caseRec.Need_To_Notify_Customer__c = true;
                updateCases.add(caseRec);
            }
            //Updating Case Notify Customer Field
                if(updateCases.size() > 0){
                    UPDATE updateCases;
                }
            system.debug('updateCases ++ '+updateCases);
        }
    }
    
    public void finish(Database.BatchableContext BC){
        
    }
    
}