force-app/main/default/objects/Case/fields/Assessment_Quality__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Quality__c</fullName>
    <label>Assessment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Be Assessed</fullName>
            </value>
            <value>
                <fullName>At Verification</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Urgent</fullName>
            </value>
            <value>
                <fullName>Ready To Lodge</fullName>
            </value>
            <value>
                <fullName>Lodged</fullName>
            </value>
            <value>
                <fullName>Conditionally Approved</fullName>
            </value>
            <value>
                <fullName>-</fullName>
                <isActive>false</isActive>
                <label>-</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <label>Sub-Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Call 1 Made</fullName>
            </value>
            <value>
                <fullName>Call 2 Made</fullName>
            </value>
            <value>
                <fullName>Follow up Date</fullName>
            </value>
            <value>
                <fullName>Chase</fullName>
            </value>
            <value>
                <fullName>Correspondence Received</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Response</fullName>
            </value>
            <value>
                <fullName>Requires Driva Action</fullName>
            </value>
            <value>
                <fullName>Follow up Date Set</fullName>
            </value>
            <value>
                <fullName>Declinature Sent</fullName>
            </value>
            <value>
                <fullName>Settlement in Progress</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Ready for Lodgement</fullName>
            </value>
            <value>
                <fullName>Cold Lead</fullName>
            </value>
            <value>
                <fullName>Withdraw Request</fullName>
            </value>
            <value>
                <fullName>Document Received</fullName>
            </value>
            <value>
                <fullName>-</fullName>
                <isActive>false</isActive>
                <label>-</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case__c/Case__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Not Dealers</label>
</CustomObject>

force-app/main/default/objects/Entitlement/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Entitlements</relationshipLabel>
    <relationshipName>Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement_Account__c/Entitlement_Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Entitlement Account</label>
</CustomObject>

force-app/main/default/objects/Milestone_Owner_Details__c/Milestone_Owner_Details__c.object-meta.xml
<CustomObject>
    <label>Milestone Owner Details</label>
    <nameField>
        <displayFormat>MOD-{0000}</displayFormat>
        <label>Milestone Owner Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestone Owner Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone_Owner_Details__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Milestone Owner Details</relationshipLabel>
    <relationshipName>Milestone_Owner_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone_Owner_Details__c/fields/Milestone_Name__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Name__c</fullName>
    <label>Milestone Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MilestoneHelperTest.cls
@isTest
private class MilestoneHelperTest {
    @testSetup static void CaseCreation() {
        List<Account> accData = new list<Account>();
        Account acc1 = new Account(Name = 'Dealer'); // Created to get specific Entitlement_Account__c from Custom Settings
        Account acc2 = new Account(Name = 'CARS24'); // Created for Case.Partner_Account__c
        accData.add(acc1);
        accData.add(acc2);
        Insert accData;
        
        insert new Entitlement_Account__c(AccountId__c = accData[0].Id, Name = 'Dealer');
        
        List<SlaProcess> sla = [Select Id from SlaProcess where Name = 'VerificationDev26' AND IsActive = True];
        
        Entitlement entObject  = new Entitlement();
        entObject.SlaProcessId = sla[0].id;
        entObject.AccountId = accData[0].id;
        entObject.Name = 'SLA';
        entObject.StartDate = system.today();
        entObject.EndDate = system.today().addDays(10);
        insert entObject;
        
        Case caseRecord = new Case(Partner_Account__c = accData[1].Id, Status = 'Under Review',
                            Sub_Status__c = 'Requires Driva Action', Assessment_Quality__c = 'To Be Assessed');
        insert caseRecord;
    }
    
    @isTest static void completeMilestone_Test() {
        Case caseRecord = [select Id, Assessment_Quality__c FROM Case WHERE Assessment_Quality__c = 'To Be Assessed'];
        test.startTest();
            caseRecord.Assessment_Quality__c = 'At Verification';
            update caseRecord;
       // MilestoneHelper.testCover();
        test.stopTest();
        Integer caseMileStoneCount = [SELECT count() FROM CaseMilestone WHERE CaseId =: caseRecord.Id AND 
                                      MilestoneType.Name = 'Initial Verification' AND IsCompleted = true];
        Integer MODCount = [SELECT count() FROM Milestone_Owner_Details__c
                            where Case__c =: caseRecord.Id AND Completed__c = true AND Milestone_Name__c = 'Initial Verification'];
        
        Assert.areEqual(1, caseMileStoneCount, 'Initial Verification Milestone should be completed');
        Assert.areEqual(1, MODCount, 'Milestone Owner Details should be completed');
        
    }
}