force-app/main/default/objects/Case/fields/Assessment_Quality__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Quality__c</fullName>
    <label>Assessment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Be Assessed</fullName>
            </value>
            <value>
                <fullName>At Verification</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Urgent</fullName>
            </value>
            <value>
                <fullName>Ready To Lodge</fullName>
            </value>
            <value>
                <fullName>Lodged</fullName>
            </value>
            <value>
                <fullName>Conditionally Approved</fullName>
            </value>
            <value>
                <fullName>-</fullName>
                <isActive>false</isActive>
                <label>-</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Need_To_Notify_Customer__c.field-meta.xml
<CustomField>
    <fullName>Need_To_Notify_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Need To Notify Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SendEmailSMSAlertsBatchTest.cls
@isTest
public class SendEmailSMSAlertsBatchTest {
    @isTest
    static void test(){
        Contact conRec = new Contact();
        conRec.LastName = 'Test';
        conRec.Email = 'abc@testgmail.com';
        Insert conRec;
        
        Case objcase = new Case();
        objcase.Status = 'Under Review';
        objcase.Origin = 'Email';
        objcase.Need_To_Notify_Customer__c = true;
        objcase.Assessment_Quality__c = 'To Be Assessed';
        objcase.ContactId = conRec.Id;
        insert objcase;
          

        
        Test.startTest();
            SendEmailSMSAlertsBatch batchObj = new SendEmailSMSAlertsBatch(System.Today());
            Database.executeBatch(batchObj);
        Test.stopTest();
    }
    @isTest
    static void testElse(){
        Contact conRec = new Contact();
        conRec.LastName = 'Test';
        conRec.Email = 'abc@testgmail.com';
        Insert conRec;
        
        Case objcase = new Case();
        objcase.Status = 'Under Review';
        objcase.Origin = 'Email';
        objcase.Need_To_Notify_Customer__c = true;
        objcase.Assessment_Quality__c = 'To Be Assessed';
        objcase.ContactId = conRec.Id;
        insert objcase;
        Date satDate;
        for(Integer i = 0; i<6; i++){
            Date d = System.today().addDays(i);
            Datetime dt = (DateTime)d;
            String dayOfWeek = dt.format('EEEE'); //This returns - Monday, Tuesday, Wednesday, etc..
            if(dayOfWeek == 'Saturday'){
                satDate = d;
                break;
            }
        }
        Test.startTest();
            SendEmailSMSAlertsBatch batchObj = new SendEmailSMSAlertsBatch(satDate);
            Database.executeBatch(batchObj);
        Test.stopTest();
    }
   
    @isTest
    static void testSchedule(){
        Test.StartTest();
        ScheduleSendEmailSMSAlertBatch testsche = new ScheduleSendEmailSMSAlertBatch();
        String sch = '0 0 23 * * ?';
        system.schedule('Test status Check', sch, testsche );
        Test.stopTest();
    }
}