force-app/main/default/objects/Case/fields/Call_Experiment__c.field-meta.xml
<CustomField>
    <fullName>Call_Experiment__c</fullName>
    <description>Field to manually update to accurately track how many calls a customer receives in the experiment cohort</description>
    <label>Call Experiment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Call 1 Made</fullName>
            </value>
            <value>
                <fullName>Call 2 Made</fullName>
            </value>
            <value>
                <fullName>Call 3 Made</fullName>
            </value>
            <value>
                <fullName>Call 4 Made</fullName>
            </value>
            <value>
                <fullName>Call 5 Made</fullName>
            </value>
            <value>
                <fullName>Call 6 Made</fullName>
            </value>
            <value>
                <fullName>Call 7 Made</fullName>
            </value>
            <value>
                <fullName>Call 8 Made</fullName>
            </value>
            <value>
                <fullName>Call 9 Made</fullName>
            </value>
            <value>
                <fullName>Call 10 Made</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Driva_UUID__c.field-meta.xml
<CustomField>
    <fullName>Driva_UUID__c</fullName>
    <label>Driva UUID</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/SyncCaseToDrivaDBTest.cls
@isTest
private class SyncCaseToDrivaDBTest {
    @isTest 
    public static void testMethod1() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        Trigger_Status__c triggerstatus = new Trigger_Status__c();
        triggerstatus.name = 'SyncCaseToDrivaDB';
        triggerstatus.Trigger_Name__c = 'SyncCaseToDrivaDB';
        triggerstatus.IsActive__c = True;
        insert triggerstatus;
        
        Case c = new case();
        c.Status = 'Received';
        c.Driva_UUID__c='ABC123';
        c.Call_Experiment__c = 'Call 1 Made';
        c.Origin = 'Phone';
        
        // Perform test
        Test.startTest();
        EntryURL.isFromBrowser = true;
        Database.SaveResult result = Database.insert(c, false);
        EntryURL.isFromBrowser = false;
        Database.SaveResult result2 = Database.insert(c, false);
        Test.stopTest();
        
        System.assert(result.isSuccess());
        System.assert(!result2.isSuccess());
    }
}