force-app/main/default/objects/Case/fields/Driva_UUID__c.field-meta.xml
<CustomField>
    <fullName>Driva_UUID__c</fullName>
    <label>Driva UUID</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Angle</fullName>
            </value>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>BFS</fullName>
            </value>
            <value>
                <fullName>Finance One</fullName>
            </value>
            <value>
                <fullName>GetCapital</fullName>
            </value>
            <value>
                <fullName>Grow</fullName>
            </value>
            <value>
                <fullName>Latitude</fullName>
            </value>
            <value>
                <fullName>Liberty</fullName>
            </value>
            <value>
                <fullName>Macquarie</fullName>
            </value>
            <value>
                <fullName>Metro</fullName>
            </value>
            <value>
                <fullName>Money3</fullName>
            </value>
            <value>
                <fullName>MoneyPlace</fullName>
            </value>
            <value>
                <fullName>Now Finance</fullName>
            </value>
            <value>
                <fullName>Pepper</fullName>
            </value>
            <value>
                <fullName>Society One</fullName>
            </value>
            <value>
                <fullName>Afs</fullName>
            </value>
            <value>
                <fullName>Finance One Commercial</fullName>
            </value>
            <value>
                <fullName>Liberty Commercial</fullName>
            </value>
            <value>
                <fullName>Macquarie Commercial</fullName>
            </value>
            <value>
                <fullName>Pepper Commercial</fullName>
            </value>
            <value>
                <fullName>Prospa</fullName>
            </value>
            <value>
                <fullName>Plenti PL</fullName>
            </value>
            <value>
                <fullName>SocietyOne</fullName>
            </value>
            <value>
                <fullName>St.George</fullName>
            </value>
            <value>
                <fullName>Westpac</fullName>
            </value>
            <value>
                <fullName>Wisr PL</fullName>
            </value>
            <value>
                <fullName>Plenti Commercial</fullName>
            </value>
            <value>
                <fullName>Firstmac</fullName>
            </value>
            <value>
                <fullName>Plenti</fullName>
            </value>
            <value>
                <fullName>Wisr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LodgeControllerTest.cls
/*************************** 
* @Name          LodgeControllerTest.cls
* @Author        vasu@driva.com.au
* @Date          29/04/2022
* @description   Test class
******************************************************
/* MODIFICATION LOG
* Version          Developer          Date               Description
*-----------------------------------------------------------------------
*  1.0              Vasu      29/04/2022          Test Class for LodgeController.cls
****************************** */
@isTest 
public class LodgeControllerTest {
	@isTest 
    public static void unit1(){
        Case obj = new Case();
        obj.Status = 'New';
        obj.Origin = 'Phone';
        obj.Subject = 'Test';
        obj.Lender__c = 'Finance One';
        obj.Driva_UUID__c = '9cb40e48-774d-4f05-af6d-66f8f0066a80';
        //da761cc1-b79b-4b34-8f9d-fb7d13e5a0a0
        insert obj;
        LodgeController.getCaseDetail(obj.Id);
        LodgeController.callLodgeSelectAPI('');
        LodgeController.callLodgeAPI('','','');
        LodgeController.processResponse(new List<String>{'test'}, null);
    }
}