force-app/main/default/objects/Case/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Angle</fullName>
            </value>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>BFS</fullName>
            </value>
            <value>
                <fullName>Finance One</fullName>
            </value>
            <value>
                <fullName>GetCapital</fullName>
            </value>
            <value>
                <fullName>Grow</fullName>
            </value>
            <value>
                <fullName>Latitude</fullName>
            </value>
            <value>
                <fullName>Liberty</fullName>
            </value>
            <value>
                <fullName>Macquarie</fullName>
            </value>
            <value>
                <fullName>Metro</fullName>
            </value>
            <value>
                <fullName>Money3</fullName>
            </value>
            <value>
                <fullName>MoneyPlace</fullName>
            </value>
            <value>
                <fullName>Now Finance</fullName>
            </value>
            <value>
                <fullName>Pepper</fullName>
            </value>
            <value>
                <fullName>Society One</fullName>
            </value>
            <value>
                <fullName>Afs</fullName>
            </value>
            <value>
                <fullName>Finance One Commercial</fullName>
            </value>
            <value>
                <fullName>Liberty Commercial</fullName>
            </value>
            <value>
                <fullName>Macquarie Commercial</fullName>
            </value>
            <value>
                <fullName>Pepper Commercial</fullName>
            </value>
            <value>
                <fullName>Prospa</fullName>
            </value>
            <value>
                <fullName>Plenti PL</fullName>
            </value>
            <value>
                <fullName>SocietyOne</fullName>
            </value>
            <value>
                <fullName>St.George</fullName>
            </value>
            <value>
                <fullName>Westpac</fullName>
            </value>
            <value>
                <fullName>Wisr PL</fullName>
            </value>
            <value>
                <fullName>Plenti Commercial</fullName>
            </value>
            <value>
                <fullName>Firstmac</fullName>
            </value>
            <value>
                <fullName>Plenti</fullName>
            </value>
            <value>
                <fullName>Wisr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <formula>Vehicle_Price__c  -  Deposit__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Personal_Loan__c.field-meta.xml
<CustomField>
    <fullName>Personal_Loan__c</fullName>
    <description>This field is used for Loan Purpose</description>
    <inlineHelpText>Loan Purpose Options</inlineHelpText>
    <label>Personal Loan</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Debt Consolidation</fullName>
            </value>
            <value>
                <fullName>Car</fullName>
            </value>
            <value>
                <fullName>Home Improvements</fullName>
            </value>
            <value>
                <fullName>Holiday</fullName>
            </value>
            <value>
                <fullName>Wedding</fullName>
            </value>
            <value>
                <fullName>Repairs</fullName>
            </value>
            <value>
                <fullName>Moving Costs</fullName>
            </value>
            <value>
                <fullName>Rental Bond</fullName>
            </value>
            <value>
                <fullName>Pay Utility Bills</fullName>
            </value>
            <value>
                <fullName>Pay Fees</fullName>
            </value>
            <value>
                <fullName>Solar / Battery</fullName>
            </value>
            <value>
                <fullName>Medical</fullName>
            </value>
            <value>
                <fullName>Legal / Professional Services</fullName>
            </value>
            <value>
                <fullName>Boat</fullName>
            </value>
            <value>
                <fullName>Motorbike</fullName>
            </value>
            <value>
                <fullName>Funeral Expenses</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Personal Income Tax</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AllRelatedCasesController.cls
public class AllRelatedCasesController {
    @AuraEnabled(cacheable = true)
    public static List<AllCasesWrapper> fetchRelatedCases(String caseId){      
        List<Case> caseRecords = new List<Case>([SELECT Id,ContactPhone from Case where Id =: caseId AND ContactPhone != NULL]);
        system.debug('caseRecords '+caseRecords);
        String phoneNum;
        String query;
        List<Case> relatedCases = new List<Case>();
        if(caseRecords.size() > 0){
           phoneNum = caseRecords[0].ContactPhone;
        }
        query = 'SELECT Id,CaseNumber,Status,CreatedDate,ContactId,Contact.Name,Partner_Account__c,Partner_Account__r.Name,Lender__c ,Loan_Amount__c,Personal_Loan__c,LastModifiedDate from Case where Id != : caseId AND (';
        if(String.isNotBlank(phoneNum)){
            query += ' ContactPhone =: phoneNum OR ';
        }
		query += ' ParentId  =: caseId OR Parent.Id =: caseId OR Parent.Parent.Id =: caseId OR Parent.Parent.Parent.Id =:caseId OR Parent.Parent.Parent.Parent.Id =: caseId OR Parent.Parent.Parent.Parent.Parent.Id =: caseId)';
        relatedCases = Database.query(query);
        
        
        String baseUrl = URL.getSalesforceBaseUrl().toExternalForm();
        List<AllCasesWrapper> allCasesInfo = new List<AllCasesWrapper>();
        for(Case caseRec : relatedCases){
            AllCasesWrapper wrapObj = new AllCasesWrapper();
            wrapObj.createdDate = caseRec.CreatedDate;
            wrapObj.modifiedDate = caseRec.LastModifiedDate;
            wrapObj.caseNumber = caseRec.CaseNumber;
            wrapObj.caseStatus = caseRec.Status;
            wrapObj.casePersonalLoan = caseRec.Personal_Loan__c;
            wrapObj.caseLoanAmount = caseRec.Loan_Amount__c;
            wrapObj.caseLender = caseRec.Lender__c;
            wrapObj.caseIdUrl = baseUrl+'/lightning/r/Case/'+caseRec.Id+'/view';
            if(caseRec.ContactId != NULL){
                wrapObj.contactUrl= baseUrl+'/lightning/r/Contact/'+caseRec.ContactId+'/view';
                wrapObj.contactName = caseRec.Contact.Name;
            }
            else{
                wrapObj.contactName = '';
                wrapObj.contactUrl = '';
            }
            if(caseRec.Partner_Account__c != NULL){
                wrapObj.partnerAccName = caseRec.Partner_Account__r.Name;
                wrapObj.partnerAccUrl = baseUrl+'/lightning/r/Account/'+caseRec.Partner_Account__c+'/view';
            }
            else{
                wrapObj.partnerAccUrl = '';
                wrapObj.partnerAccName = '';
            }
            allCasesInfo.add(wrapObj);
        }
        return allCasesInfo;
    }
    public class AllCasesWrapper{
        
        @AuraEnabled
        public DateTime createdDate;
        @AuraEnabled
        public DateTime modifiedDate;
        @AuraEnabled
        public String partnerAccName;
        @AuraEnabled
        public String partnerAccUrl;
        @AuraEnabled
        public String contactName;
        @AuraEnabled
        public String contactUrl;
        @AuraEnabled
        public String caseIdUrl;
        @AuraEnabled
        public String caseNumber;
        @AuraEnabled
        public String caseStatus;
        @AuraEnabled
        public String caseLender;
        @AuraEnabled
        public Decimal caseLoanAmount;
        @AuraEnabled
        public String casePersonalLoan;
    }
}