force-app/main/default/objects/Case/fields/Need_To_Notify_Customer__c.field-meta.xml
<CustomField>
    <fullName>Need_To_Notify_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Need To Notify Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case__c/Case__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Not Dealers</label>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Email_When_Case_In_UR__mdt/Email_When_Case_In_UR__mdt.object-meta.xml
<CustomObject>
    <label>Email When Case In UR</label>
    <pluralLabel>Email When Case In UR</pluralLabel>
</CustomObject>

force-app/main/default/objects/Email_When_Case_In_UR__mdt/fields/Email_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Developer_Name__c</fullName>
    <label>Email Developer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/smagicinteract__Converse_App_Task__c/smagicinteract__Converse_App_Task__c.object-meta.xml
<CustomObject>
    <label>Converse App Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Converse App Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/smagicinteract__Converse_App_Task__c/fields/case__c.field-meta.xml
<CustomField>
    <fullName>case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Converse App Tasks</relationshipLabel>
    <relationshipName>converse_app_tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/smagicinteract__Converse_App_Task__c/fields/smagicinteract__Automation_Key_Reference__c.field-meta.xml
<CustomField>
    <fullName>smagicinteract__Automation_Key_Reference__c</fullName>
    <description>This field contains the automation key reference.</description>
    <label>Automation Key Reference</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/smagicinteract__Converse_App_Task__c/fields/smagicinteract__Contact__c.field-meta.xml
<CustomField>
    <fullName>smagicinteract__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains the ID of the related contact.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Converse App Tasks</relationshipLabel>
    <relationshipName>Converse_App_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/smagicinteract__Converse_App_Task__c/fields/smagicinteract__Template__c.field-meta.xml
<CustomField>
    <fullName>smagicinteract__Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains the ID of the related template.</description>
    <label>Template</label>
    <referenceTo>smagicinteract__SMS_Template__c</referenceTo>
    <relationshipLabel>Converse App Tasks</relationshipLabel>
    <relationshipName>Converse_App_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/smagicinteract__SMS_Template__c/smagicinteract__SMS_Template__c.object-meta.xml
<CustomObject>
    <customHelpPage>smagicinteract__SMSMagicHelp</customHelpPage>
    <description>SMS Template is similar to Email template, it gives way to add personalization to bulk sms&apos;ing.</description>
    <label>Converse Template</label>
    <nameField>
        <displayFormat>ST-{00000000}</displayFormat>
        <label>Converse Template Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Converse Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/smagicinteract__smsMagic__c/smagicinteract__smsMagic__c.object-meta.xml
<CustomObject>
    <customHelpPage>smagicinteract__SMSMagicHelp</customHelpPage>
    <description>SMSMagic object in Interact, This is basic Object which stores information about Outgoing SMS.</description>
    <label>SMS History</label>
    <nameField>
        <displayFormat>SM-{000000000}</displayFormat>
        <label>Record number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/smagicinteract__smsMagic__c/fields/smagicinteract__Case__c.field-meta.xml
<CustomField>
    <fullName>smagicinteract__Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains the ID of the related Case.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>SMS History</relationshipLabel>
    <relationshipName>SMS_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/smagicinteract__smsMagic__c/fields/smagicinteract__Contact__c.field-meta.xml
<CustomField>
    <fullName>smagicinteract__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains the ID of the related Contact.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>smsMagic</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/smagicinteract__smsMagic__c/fields/smagicinteract__Converse_App_Task__c.field-meta.xml
<CustomField>
    <fullName>smagicinteract__Converse_App_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains the ID of the related Converse App Task.</description>
    <label>Converse App Task</label>
    <referenceTo>smagicinteract__Converse_App_Task__c</referenceTo>
    <relationshipLabel>SMS History</relationshipLabel>
    <relationshipName>SMS_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/smagicinteract__smsMagic__c/fields/smagicinteract__SMS_Template__c.field-meta.xml
<CustomField>
    <fullName>smagicinteract__SMS_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains the ID of the related SMS template.</description>
    <label>SMS Template</label>
    <referenceTo>smagicinteract__SMS_Template__c</referenceTo>
    <relationshipLabel>SMS History</relationshipLabel>
    <relationshipName>SMS_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/smagicinteract__smsMagic__c/fields/smagicinteract__SMSText__c.field-meta.xml
<CustomField>
    <fullName>smagicinteract__SMSText__c</fullName>
    <description>This field contains the text sent to recipient.</description>
    <label>SMSText</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SMSTemplateWhenCaseInUR__mdt/SMSTemplateWhenCaseInUR__mdt.object-meta.xml
<CustomObject>
    <label>SMS When Case In UR</label>
    <pluralLabel>SMS When Case In UR</pluralLabel>
</CustomObject>

force-app/main/default/classes/SendEmailSMSAlertsBatchHelper.cls
public class SendEmailSMSAlertsBatchHelper {
    
    public static boolean skipStopMailSend = false;
    public static void sendEmailAndSMS(List<Case> caseRecords){
        //send mail and sms alerts
        List<Case> updateCases = new List<Case>();
        List<Messaging.SingleEmailMessage> emailMessages = new List<Messaging.SingleEmailMessage>();
        List<smagicinteract__Converse_App_Task__c> smsMessages = new List<smagicinteract__Converse_App_Task__c>();
        List<smagicinteract__smsMagic__c> smschatterlist = new List<smagicinteract__smsMagic__c>();
        List<SMSTemplateWhenCaseInUR__mdt> smsTemp = SMSTemplateWhenCaseInUR__mdt.getAll().values();
        String smsTempName;
        if(smsTemp.size() > 0){
            smsTempName = smsTemp[0].Label;
        }
        List<Email_When_Case_In_UR__mdt> emailTemplate = Email_When_Case_In_UR__mdt.getAll().values();
        String emailName;
        if(emailTemplate.size() > 0 ){
            emailName = emailTemplate[0].Email_Developer_Name__c;
        }
        EmailTemplate emt = [SELECT Id,DeveloperName from EmailTemplate where DeveloperName =: emailName];
        System.debug('email template name'+emt.developerName);
        smagicinteract__SMS_Template__c smsTemplate=new smagicinteract__SMS_Template__c();
        if(!Test.isRunningTest()){
        smsTemplate = [SELECT Id,Name FROM smagicinteract__SMS_Template__c where Name =: smsTempName];
        }
        //System.debug('smstemplate name'+smsTemplate.Name);
       //EmailTemplate emt = [SELECT Id from EmailTemplate where DeveloperName = 'Email_When_Case_in_UR_and_To_Be_Assessed_1663209541064']; 
       // EmailTemplate emt = [SELECT Id from EmailTemplate where DeveloperName = 'Email_When_Case_in_UR_and_To_Be_Assessed_1663308011246']; // Prod template developerName
        
       // smagicinteract__SMS_Template__c smsTemplate = [SELECT Id,Name FROM smagicinteract__SMS_Template__c where Name = 'ST-00000031']; //Add SMSTemplateName in Dev
        //smagicinteract__SMS_Template__c smsTemplate = [SELECT Id,Name FROM smagicinteract__SMS_Template__c where Name = 'ST-00000033']; // Add SMSTemplateName different  in PROD
        for(Case caseObj : caseRecords){
            if(caseObj.ContactEmail != NULL){
                OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'contact@driva.com.au'];
                Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                message.setToAddresses(new List<String>{caseObj.ContactEmail});
                //message.setSenderDisplayName('Driva');
                if(owea.size()>0){
                    message.setOrgWideEmailAddressId(owea.get(0).Id);  
                }
                
                message.setTemplateId(emt.id);
                message.setTargetObjectId(caseObj.ContactId);
                message.setTreatTargetObjectAsRecipient(false);
                message.setWhatId(caseObj.Id);
                emailMessages.add(message);
            }                
            if(!Test.isRunningTest()){
            smagicinteract__Converse_App_Task__c smsObj = new smagicinteract__Converse_App_Task__c();
            smsObj.Name = caseObj.Id;
            smsObj.case__c = caseObj.Id; //this field was not in the sandbox: DemoOrg
            smsObj.smagicinteract__Automation_Key_Reference__c = 'PA-000020';// sandbox id :PA-000020
            smsObj.smagicinteract__Contact__c = caseObj.ContactId;
            smsObj.smagicinteract__Template__c = smsTemplate.Id; //SMS Template ID            
            smsMessages.add(smsObj);
            }
            //post SMS text to chatter
           
            smagicinteract__smsMagic__c smschatter=new smagicinteract__smsMagic__c();
            smschatter.smagicinteract__Case__c=caseObj.Id;
            smschatter.smagicinteract__SMSText__c=smsTemplate.Name;// template text to post to chatter
            smschatterlist.add(smschatter);
             
            //updating the notify customer field as false 
            if(caseObj.Need_To_Notify_Customer__c){
                Case caseRec = new Case(Id = caseObj.Id);
                caseRec.Need_To_Notify_Customer__c = false;
                updateCases.add(caseRec);
            }
            
        }
        //Sending mails
        try {
            skipStopMailSend = true;
            Messaging.sendEmail(emailMessages);
            
            //Inserting SMSs 
            if(smsMessages.size() > 0){
                INSERT smsMessages;
            }
            
            //Updating Case Notify Customer Field
            if(updateCases.size() > 0){
                UPDATE updateCases;
            }
            
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
    }
}