force-app/main/default/objects/Case/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <label>Sub-Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Call 1 Made</fullName>
            </value>
            <value>
                <fullName>Call 2 Made</fullName>
            </value>
            <value>
                <fullName>Follow up Date</fullName>
            </value>
            <value>
                <fullName>Chase</fullName>
            </value>
            <value>
                <fullName>Correspondence Received</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Response</fullName>
            </value>
            <value>
                <fullName>Requires Driva Action</fullName>
            </value>
            <value>
                <fullName>Follow up Date Set</fullName>
            </value>
            <value>
                <fullName>Declinature Sent</fullName>
            </value>
            <value>
                <fullName>Settlement in Progress</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Ready for Lodgement</fullName>
            </value>
            <value>
                <fullName>Cold Lead</fullName>
            </value>
            <value>
                <fullName>Withdraw Request</fullName>
            </value>
            <value>
                <fullName>Document Received</fullName>
            </value>
            <value>
                <fullName>-</fullName>
                <isActive>false</isActive>
                <label>-</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Note__c/Note__c.object-meta.xml
<CustomObject>
    <label>Note</label>
    <nameField>
        <displayFormat>N-{00000000}</displayFormat>
        <label>Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Note</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Note__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Created_At__c.field-meta.xml
<CustomField>
    <fullName>Created_At__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Created At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Created_By__c.field-meta.xml
<CustomField>
    <fullName>Created_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Created By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Note</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Note</relationshipLabel>
    <relationshipName>Partner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Partner_User_Email__c.field-meta.xml
<CustomField>
    <fullName>Partner_User_Email__c</fullName>
    <label>Partner User Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Poster__c.field-meta.xml
<CustomField>
    <fullName>Poster__c</fullName>
    <description>Poster, either driva user or partner user</description>
    <formula>IF(ISNULL(Partner_User_Email__c) || ISBLANK(Partner_User_Email__c), HYPERLINK(&quot;/lightning/r/User/&quot;+CreatedById+&quot;/view&quot;, CreatedBy.FirstName + &quot; &quot; + CreatedBy.LastName) , HYPERLINK(&quot;lightning/r/Account/&quot;+Partner__c+&quot;/view&quot;, Partner__r.Name) + &quot; Email: &quot; + Partner_User_Email__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Poster</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Public__c.field-meta.xml
<CustomField>
    <fullName>Public__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Related_Case__c.field-meta.xml
<CustomField>
    <fullName>Related_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Note</relationshipLabel>
    <relationshipName>Note</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DrivaNoteApex.cls
public class DrivaNoteApex {
    @AuraEnabled
    //Quick text-Experiment
    public static list<QuickTextWrapper> getAllQuickText(){
        List<QuickTextWrapper> quickTexts = new List<QuickTextWrapper>();
        for(QuickText obj : [SELECT Id, Name, Message FROM QuickText Order by Name limit 200]){
            QuickTextWrapper quickObj = new QuickTextWrapper();
            quickObj.label = obj.Name;
            quickObj.value = obj.Message;
            quickTexts.add(quickObj);
        }
        return quickTexts;
    }
    @AuraEnabled
    //Quick text-Experiment
    public static String fetchQuickText(String Id){
        String message = '';
        for(QuickText obj : [SELECT Id, Name, Message FROM QuickText Where Id =: Id]){
            message = obj.Message;
        }
        return message;
    }
    public class QuickTextWrapper{
        @AuraEnabled
        public String label{get;set;}
        @AuraEnabled
        public String value{get;set;}
    }
    @AuraEnabled
    //Quick text -Experiment
    public static list<Note__c> getAllNotes(string caseId)
    {
        List<Note__c> notesList=new List<Note__c>();
        
        for(Note__c obj:[Select id, Poster__c, Public__c, format(Created_At__c) Created_At__c, Created_By__c, Content__c, Created_By__r.FirstName, Created_By__r.MiddleName, Created_By__r.LastName, Partner__c, Partner__r.Name, Partner_User_Email__c,Related_Case__r.Sub_Status__c from Note__c where Related_Case__c=:caseId ORDER BY Created_At__c desc limit 200])
        {
            notesList.add(obj);
        }
        return notesList;
    }
    
    @AuraEnabled
   // public static void addNewNote(string createdBy, string caseId, boolean isPublic, string content,List<String> usersIds)
    public static void addNewNote(string createdBy, string caseId, boolean isPublic, string content)
    {
        Note__c note = new Note__c();
        note.Created_By__c = createdBy;
        note.Related_Case__c = caseId;
        //note.Related_Case__r.Sub_Status__c= 'Correspondence Received';
        note.Public__c = isPublic;
        note.Content__c = content;
        Database.insert(note);
        //Case c=new Case();
        //c.Id=caseId;
       // c.Sub_Status__c='Correspondence Received';
       // if(note.Related_Case__c !=''){
        //    Database.upsert(c);
       // }
       /* system.debug('Note===>'+note);
        system.debug('usersIds===>'+usersIds);
        if(note.Id != NULL && usersIds != NULL && usersIds.size() > 0 ){
            DrivaNoteApex.sendNotifications(usersIds,content,note.id);
        }*/
    }
    
    @AuraEnabled
    public static void addFeeditem(string caseId, string body)
    {
        FeedItem post = new FeedItem();
        post.ParentId =caseId;
        post.Body = body;
        post.isRichText = true;
        Database.insert(post);
    }
    //Added 1-8-2022 
    @AuraEnabled
    public static List<QuickTextWrapper> getAllUsers(){
        
        List<QuickTextWrapper> allUsers = new List<QuickTextWrapper>();
        for(User usr : [SELECT Id,Email,Name FROM User where IsActive = true]){
            QuickTextWrapper user = new QuickTextWrapper();
            user.label = usr.Name;
            user.value = usr.Id;
            allUsers.add(user);
            
        }
        system.debug('allUsers'+allUsers);
        return allUsers;
    }
   /* public static void sendNotifications(List<String> usersIds,String content,String noteId){
        Set<String> userSet = new Set<String>();        
        userSet.addAll(usersIds);
        List<CustomNotificationType > TemplateInfoDetail = [SELECT Id,DeveloperName FROM CustomNotificationType                                                        
                                                            WHERE DeveloperName='Notes_Notification'];   
        
        // Create a new custom notification                
        Messaging.CustomNotification currNotification = new Messaging.CustomNotification();                
        // Set the contents                
        currNotification.setTitle('You have received new note');   
        String plainText = content.stripHtmlTags();
        currNotification.setBody(''+plainText);                
        // Set the notification type and target                
        currNotification.setNotificationTypeId(TemplateInfoDetail[0].Id);               
        currNotification.setTargetId(noteId);
        
        try {                    
            currNotification.send(userSet);                  
        }                
        catch (Exception ex) {                    
            System.debug('Notification Failed: ' + ex.getMessage());                    
        }
        
    }*/
}