force-app/main/default/objects/Case/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <label>Sub-Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Call 1 Made</fullName>
            </value>
            <value>
                <fullName>Call 2 Made</fullName>
            </value>
            <value>
                <fullName>Follow up Date</fullName>
            </value>
            <value>
                <fullName>Chase</fullName>
            </value>
            <value>
                <fullName>Correspondence Received</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Response</fullName>
            </value>
            <value>
                <fullName>Requires Driva Action</fullName>
            </value>
            <value>
                <fullName>Follow up Date Set</fullName>
            </value>
            <value>
                <fullName>Declinature Sent</fullName>
            </value>
            <value>
                <fullName>Settlement in Progress</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Ready for Lodgement</fullName>
            </value>
            <value>
                <fullName>Cold Lead</fullName>
            </value>
            <value>
                <fullName>Withdraw Request</fullName>
            </value>
            <value>
                <fullName>Document Received</fullName>
            </value>
            <value>
                <fullName>-</fullName>
                <isActive>false</isActive>
                <label>-</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case__c/Case__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Not Dealers</label>
</CustomObject>

force-app/main/default/objects/Document_Library__c/Document_Library__c.object-meta.xml
<CustomObject>
    <label>Document Library</label>
    <nameField>
        <label>Document Library Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Library</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Library__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Document Library</relationshipLabel>
    <relationshipName>Document_Library</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Document_Library__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Error_Handler__c/Error_Handler__c.object-meta.xml
<CustomObject>
    <label>Error Handler</label>
    <nameField>
        <label>Error Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Handler__c/fields/Document_Library__c.field-meta.xml
<CustomField>
    <fullName>Document_Library__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Library</label>
    <referenceTo>Document_Library__c</referenceTo>
    <relationshipLabel>Error Handlers</relationshipLabel>
    <relationshipName>Error_Handlers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Error_Handler__c/fields/Response_Code__c.field-meta.xml
<CustomField>
    <fullName>Response_Code__c</fullName>
    <label>Response Code</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Error_Handler__c/fields/Response_Message__c.field-meta.xml
<CustomField>
    <fullName>Response_Message__c</fullName>
    <label>Response Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DocumentLibraryTrigger_Handler.cls
/*
* Created By : NRUPA VORA
* Date : 12/01/2022
* Description : When Document Library Inserts send post call out to driva with Document Library Id
*/
public class DocumentLibraryTrigger_Handler {
    
    //METHOD CALLED FROM TRIGGER ON INSERTING DOCUMENT LIBRARY
    @future(callout=true)
    public static void InsertPostCallout(set<Id> NewDocumentIds){
        IF(NewDocumentIds.size()>0){
            List<Document_Library__c> DocumentList = [SELECT Id, Is_Deleted__c FROM Document_Library__c WHERE Id IN: NewDocumentIds];
            IF(DocumentList.size()>0){
                List<Error_Handler__c> Errors = new List<Error_Handler__c>();
                FOR(Document_Library__c Document : DocumentList){
                    
                    Http http = new Http();
                    HttpRequest request = new HttpRequest();
                    
                    // Use NamedCredentials & callout to get Bearer JWT
                    string url = 'callout:Salesforce_Service/file';
                    request.setEndpoint(url);

                    IF(Document.Is_Deleted__c){
                        request.setMethod('DELETE');
                    }
                    ELSE{
                        request.setMethod('POST');
                    }
                    request.setHeader('Content-Type', 'application/json;charset=UTF-8');
                    request.setBody('{"Id":"'+Document.Id+'"}');
                    
                    // Merge fields after setBody
                    request.setHeader('Authorization', '{!$Credential.Password}');
                    
                    HttpResponse response = http.send(request);
                    System.debug('response :: '+response);
                    IF(response != null){
                        Integer StatusCode = response.getStatusCode();
                        String StatusMessage = response.getStatus();
                        System.debug('StatusCode '+StatusCode);
                        System.debug('StatusMessage '+StatusMessage);
                        IF(response.getStatusCode() != 200){
                            System.debug('creating new Error Handler');
                            Error_Handler__c Error = new Error_Handler__c();
                            Error.Response_Code__c = StatusCode;
                            Error.Response_Message__c = StatusMessage;
                            Error.Document_Library__c = Document.Id;
                            Errors.add(Error);
                        }
                    }
                }
                IF(Errors.size()>0){
                    INSERT Errors;
                }
            }
        }
    }
    
    //METHOD CALLED FROM TRIGER WHEN RECORD SOFT DELETE
    @future(callout=true)
    public static void DeleteCallout(set<Id> UpdatedDocumentId){
        IF(UpdatedDocumentId.size()>0){
            List<Document_Library__c> DocumentList = [SELECT Id, Is_Deleted__c FROM Document_Library__c WHERE Id IN: UpdatedDocumentId];
            IF(DocumentList.size()>0){
                List<Error_Handler__c> Errors = new List<Error_Handler__c>();
                FOR(Document_Library__c Document : DocumentList){
                    IF(Document.Is_Deleted__c){
            
                        Http http = new Http();
                        HttpRequest request = new HttpRequest();

                        // Use NamedCredentials & callout to get Bearer JWT
                        string url = 'callout:Salesforce_Service/file/' + Document.Id;
                        request.setEndpoint(url);
                        request.setMethod('DELETE');
                        request.setHeader('Content-Type', 'application/json;charset=UTF-8');
              
                        request.setBody('{"Id":"'+Document.Id+'"}');

                        // Merge fields after setBody
                        request.setHeader('Authorization', '{!$Credential.Password}');
                        
                        HttpResponse response = http.send(request);
                        System.debug('response :: '+response);
                        IF(response != null){
                            Integer StatusCode = response.getStatusCode();
                            String StatusMessage = response.getStatus();
                            System.debug('StatusCode '+StatusCode);
                            System.debug('StatusMessage '+StatusMessage);
                            IF(response.getStatusCode() != 200){
                                System.debug('creating new Error Handler');
                                Error_Handler__c Error = new Error_Handler__c();
                                Error.Response_Code__c = StatusCode;
                                Error.Response_Message__c = StatusMessage;
                                Error.Document_Library__c = Document.Id;
                                Errors.add(Error);
                            }
                        }
                    }
                    IF(Errors.size()>0){
                        INSERT Errors;
                    }
                }
            }
        }
    }
    
    //update case sub status after document insert
    public static void updateCaseSubStatus(List<Document_Library__c> lstDoc) {
        
        System.debug('@@ in method');
        set<Id> caseIds = new set<Id>();
        
        for(Document_Library__c objDoc: lstDoc) {
            if(objDoc.Case__c != null) {
                caseIds.add(objDoc.Case__c);
            }            
        }
        
        if(caseIds.size() > 0) {
            system.debug('@@ in If');
            List<case> lstCase = [Select Id, Sub_Status__c from case where Id IN: caseIds];
            List<Case> updtlstcase = new List<Case>();
            
            System.debug('@@@ lstCase = '+lstCase);
            for(Case objCase: lstCase) {
                objCase.Sub_Status__c = 'Correspondence Received';
                updtlstcase.add(objCase);
            }
            System.debug('@@@ updtlstcase = '+updtlstcase);
            
            if(updtlstcase.size() > 0) {
                update updtlstcase;
            }
        }
    }
}