force-app/main/default/objects/Case/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <label>Sub-Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Call 1 Made</fullName>
            </value>
            <value>
                <fullName>Call 2 Made</fullName>
            </value>
            <value>
                <fullName>Follow up Date</fullName>
            </value>
            <value>
                <fullName>Chase</fullName>
            </value>
            <value>
                <fullName>Correspondence Received</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Response</fullName>
            </value>
            <value>
                <fullName>Requires Driva Action</fullName>
            </value>
            <value>
                <fullName>Follow up Date Set</fullName>
            </value>
            <value>
                <fullName>Declinature Sent</fullName>
            </value>
            <value>
                <fullName>Settlement in Progress</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Ready for Lodgement</fullName>
            </value>
            <value>
                <fullName>Cold Lead</fullName>
            </value>
            <value>
                <fullName>Withdraw Request</fullName>
            </value>
            <value>
                <fullName>Document Received</fullName>
            </value>
            <value>
                <fullName>-</fullName>
                <isActive>false</isActive>
                <label>-</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Handler__c/Error_Handler__c.object-meta.xml
<CustomObject>
    <label>Error Handler</label>
    <nameField>
        <label>Error Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Handler__c/fields/Response_Message__c.field-meta.xml
<CustomField>
    <fullName>Response_Message__c</fullName>
    <label>Response Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseQueable.cls
public class CaseQueable implements Queueable {
    public List<Case> caseList ; 
    public CaseQueable(List<Case> caseList){
        this.caseList = caseList ; 
        System.debug('@@thiscaseListCons'+ this.caseList);
    }
    public void execute(QueueableContext context) {
        /*for(Case cas :caseList){
          cas.Sub_Status__c = 'Correspondence Received'; 
        }
        System.debug('@@caseListjust'+caseList);*/
        try{
            if(caseList.size() > 0)
        	update caseList;
        }
        catch(Exception e){
            List<Error_Handler__c> Errors = new List<Error_Handler__c>();
            Error_Handler__c Error = new Error_Handler__c();
            Error.Response_Message__c = e.getMessage();
            Errors.add(Error);
            
            IF(Errors.size()>0){
                INSERT Errors;
            }
            
            system.debug(e);
        }
    }
}