force-app/main/default/objects/Case__c/Case__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Not Dealers</label>
</CustomObject>

force-app/main/default/objects/Document_Library__c/Document_Library__c.object-meta.xml
<CustomObject>
    <label>Document Library</label>
    <nameField>
        <label>Document Library Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Library</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Library__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Document Library</relationshipLabel>
    <relationshipName>Document_Library</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Document_Library__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Drivers License Front</fullName>
                <default>true</default>
                <label>Drivers License Front</label>
            </value>
            <value>
                <fullName>Drivers License Back</fullName>
            </value>
            <value>
                <fullName>Payslip One</fullName>
            </value>
            <value>
                <fullName>Payslip Two</fullName>
            </value>
            <value>
                <fullName>Bankstatements</fullName>
            </value>
            <value>
                <fullName>Manual Uploaded Bankstatements</fullName>
            </value>
            <value>
                <fullName>Privacy Policy</fullName>
            </value>
            <value>
                <fullName>Credit File</fullName>
            </value>
            <value>
                <fullName>Sales Invoice</fullName>
            </value>
            <value>
                <fullName>Insurance Certificate</fullName>
            </value>
            <value>
                <fullName>Preliminary Assessment</fullName>
            </value>
            <value>
                <fullName>Medicare</fullName>
            </value>
            <value>
                <fullName>Centrelink Income Statements</fullName>
            </value>
            <value>
                <fullName>Most Recent Tax Return</fullName>
            </value>
            <value>
                <fullName>Notice of Assessment</fullName>
            </value>
            <value>
                <fullName>Partner Declared Income</fullName>
            </value>
            <value>
                <fullName>Tenancy Agreement</fullName>
            </value>
            <value>
                <fullName>Rental Ledger</fullName>
            </value>
            <value>
                <fullName>Trust Deed</fullName>
            </value>
            <value>
                <fullName>Child Support Assessment</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Verifier</fullName>
            </value>
            <value>
                <fullName>Most Recent Partner Payslip</fullName>
            </value>
            <value>
                <fullName>Drivers Licence</fullName>
            </value>
            <value>
                <fullName>Payslips</fullName>
            </value>
            <value>
                <fullName>Partners Payslip</fullName>
            </value>
            <value>
                <fullName>Partners Payslip2</fullName>
            </value>
            <value>
                <fullName>Partners N O A</fullName>
            </value>
            <value>
                <fullName>Partners T R</fullName>
            </value>
            <value>
                <fullName>Partners N O A2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Library__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/DocumentLibraryTrigger_Test.cls
@isTest public class DocumentLibraryTrigger_Test {
    
    //THIS IS FOR 200 RESPONSE CODE
    @isTest 
    public static void testMethod1(){
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        Trigger_Status__c setting = new Trigger_Status__c();
        setting.Name = 'DocumentLibraryTrigger';
        setting.IsActive__c = true;
        insert setting;
        
        Case c = new case();
        Insert c;
        Document_Library__c document = new Document_Library__c();
        document.Case__c = c.id;
        document.Document_Type__c = 'Credit File';
       
        Insert document;
        Set<Id> documentID = new Set <Id>{document.Id};
            DocumentLibraryTrigger_Handler.InsertPostCallout(documentID);
        DocumentLibraryTrigger_Handler.DeleteCallout(documentID);
        document.Is_Deleted__c = true;
        update document;
    }
    
    public class MockHttpResponseGenerator implements HttpCalloutMock {
        // Implement this interface method
        public HTTPResponse respond(HTTPRequest req) {
            // Optionally, only send a mock response for a specific endpoint
            // and method.
            //System.assertEquals('http://example.com/example/test', req.getEndpoint());
            //System.assertEquals('GET', req.getMethod());
            
            // Create a fake response
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"example":"test"}');
            res.setStatusCode(200);
            return res;
        }
    }
    
    //THIS IS FOR 200 RESPONSE CODE
    @isTest 
    public static void testMethod2(){
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator2());
        Case c = new case();
        Insert c;
        Document_Library__c document = new Document_Library__c();
        document.Case__c = c.id;
        document.Document_Type__c = 'Credit File';
        
        Insert document;
        Set<Id> documentID = new Set <Id>{document.Id};
            DocumentLibraryTrigger_Handler.InsertPostCallout(documentID);
        DocumentLibraryTrigger_Handler.DeleteCallout(documentID);
        document.Is_Deleted__c = true;
        update document;
    }
    
    public class MockHttpResponseGenerator2 implements HttpCalloutMock {
        // Implement this interface method
        public HTTPResponse respond(HTTPRequest req) {
            // Optionally, only send a mock response for a specific endpoint
            // and method.
            //System.assertEquals('http://example.com/example/test', req.getEndpoint());
            //System.assertEquals('GET', req.getMethod());
            
            // Create a fake response
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"example":"test"}');
            res.setStatusCode(404);
            return res;
        }
    }
}