force-app/main/default/objects/Case__c/Case__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Not Dealers</label>
</CustomObject>

force-app/main/default/objects/Milestone_Owner_Details__c/Milestone_Owner_Details__c.object-meta.xml
<CustomObject>
    <label>Milestone Owner Details</label>
    <nameField>
        <displayFormat>MOD-{0000}</displayFormat>
        <label>Milestone Owner Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestone Owner Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone_Owner_Details__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Milestone Owner Details</relationshipLabel>
    <relationshipName>Milestone_Owner_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone_Owner_Details__c/fields/Milestone_Name__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Name__c</fullName>
    <label>Milestone Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MilestoneHelper.cls
global class MilestoneHelper {
    @InvocableMethod(label='Milestone Completion' description='Milestone Completion')
    // here input param is smsRequest of List type
    global static void completeMilestone(milestoneRequest[] requests){
        for (milestoneRequest request : requests) {
            List<CaseMilestone> cmsToUpdate = [select Id, completionDate
                                               from CaseMilestone cm
                                               where caseId =: request.caseId and cm.MilestoneType.Name =: request.milestoneName 
                                               and completionDate = null limit 1];
            if (cmsToUpdate.size() > 0){
                for (CaseMilestone cm : cmsToUpdate){
                    cm.completionDate = System.now();
                }
                update cmsToUpdate;
            }
            List<Milestone_Owner_Details__c> MODList = [SELECT Id, End_Date__c, Completed__c FROM Milestone_Owner_Details__c
                                               where Case__c =: request.caseId and Milestone_Name__c =: request.milestoneName 
                                               and Completed__c = null];
            if (MODList.size() > 0){
                for (Milestone_Owner_Details__c MOD : MODList){
                    MOD.End_Date__c = System.now();
                    MOD.Completed__c = true;
                }
                update MODList;
            }
        }
    }
    
    
    global class milestoneRequest {
        @InvocableVariable(required=true)
        global Id caseId;
        
        @InvocableVariable(required=true)
        global String milestoneName;
    }
    // Enable the below code as part of Iteration 2 as it has dependency on flow and remove once flow is deployed
    /*public static void testCover(){
        String test = 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
        test += 'Test';
    }*/
}