force-app/main/default/objects/Liability__c/Liability__c.object-meta.xml
<CustomObject>
    <label>Liability</label>
    <nameField>
        <displayFormat>LB-{00000}</displayFormat>
        <label>Liabilities Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Liability__c/fields/Original_Amount__c.field-meta.xml
<CustomField>
    <fullName>Original_Amount__c</fullName>
    <label>Original Amount</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/SyncLiabilityToDrivaDBTest.cls
@isTest
public class SyncLiabilityToDrivaDBTest {
	@isTest 
    public static void testMethod1() {
        
        Liability__c lia = new Liability__c();
        lia.Original_Amount__c = 100;
        
        // Perform test
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        EntryURL.isFromBrowser = true;
        Database.SaveResult result = Database.insert(lia, false);
        EntryURL.isFromBrowser = false;
        Database.SaveResult result2 = Database.insert(lia, false);
        
        Test.stopTest();
        
        System.assert(result.isSuccess());
        System.assert(!result2.isSuccess());
    }
}