force-app/main/default/objects/Additional_Income__c/Additional_Income__c.object-meta.xml
<CustomObject>
    <description>Child object of the Case object</description>
    <label>Additional Income</label>
    <nameField>
        <displayFormat>IN-{00000}</displayFormat>
        <label>Income Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Incomes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Income__c/fields/Income_Amount__c.field-meta.xml
<CustomField>
    <fullName>Income_Amount__c</fullName>
    <label>Income Amount</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/SyncAdditionalIncomeToDrivaDBTest.cls
@isTest 
public class SyncAdditionalIncomeToDrivaDBTest {
    @isTest 
    public static void testMethod1() {
        
        Trigger_Status__c triggerstatus = new Trigger_Status__c();
        triggerstatus.name = 'SyncAdditionalIncomeToDrivaDB';
        triggerstatus.Trigger_Name__c = 'SyncAdditionalIncomeToDrivaDB';
        triggerstatus.IsActive__c = True;
        insert triggerstatus;
        
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Additional_Income__c a = new Additional_Income__c();
        a.Income_Amount__c = 100;
        Additional_Income__c b = new Additional_Income__c();
        b.Income_Amount__c = 100;
        
        // Perform test
        Test.startTest();
        EntryURL.isFromBrowser = true;
        Database.SaveResult result = Database.insert(a, false);
        EntryURL.isFromBrowser = false;
        Database.SaveResult result2 = Database.insert(b, false);
        
        Test.stopTest();
        
        System.assert(result.isSuccess());
        System.assert(result2.isSuccess());
    }
}