force-app/main/default/objects/Additional_Income__c/Additional_Income__c.object-meta.xml
<CustomObject>
    <description>Child object of the Case object</description>
    <label>Additional Income</label>
    <nameField>
        <displayFormat>IN-{00000}</displayFormat>
        <label>Income Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Incomes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Income__c/fields/Income_Amount__c.field-meta.xml
<CustomField>
    <fullName>Income_Amount__c</fullName>
    <label>Income Amount</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/DeleteAdditionalIncomeToDrivaDBTest.cls
@isTest 
public class DeleteAdditionalIncomeToDrivaDBTest {
    @isTest 
    public static void testMethod1() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Additional_Income__c a = new Additional_Income__c();
        a.Income_Amount__c = 100;
        insert a;
        
        // Perform test
        Test.startTest();
        EntryURL.isFromBrowser = true;
        SyncAdditionalIncomeToDrivaDBHelper.isFirstRun = true;
		Database.DeleteResult result = Database.delete(a, false);
        EntryURL.isFromBrowser = false;
        SyncAdditionalIncomeToDrivaDBHelper.isFirstRun = true;
        Database.DeleteResult result2 = Database.delete(a, false);
        
        Test.stopTest();
        
        System.assert(result.isSuccess());
        System.assert(!result2.isSuccess());
    }
}