force-app/main/default/objects/AmazonS3__c/AmazonS3__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>AmazonS3</label>
</CustomObject>

force-app/main/default/objects/AmazonS3__c/fields/AmazonS3_BucketName__c.field-meta.xml
<CustomField>
    <fullName>AmazonS3_BucketName__c</fullName>
    <label>AmazonS3_BucketName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AmazonS3__c/fields/AmazonS3_Host__c.field-meta.xml
<CustomField>
    <fullName>AmazonS3_Host__c</fullName>
    <label>AmazonS3_Host</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AmazonS3__c/fields/AmazonS3_Key__c.field-meta.xml
<CustomField>
    <fullName>AmazonS3_Key__c</fullName>
    <label>AmazonS3_Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AmazonS3__c/fields/AmazonS3_Secret__c.field-meta.xml
<CustomField>
    <fullName>AmazonS3_Secret__c</fullName>
    <label>AmazonS3_Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case__c/Case__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Not Dealers</label>
</CustomObject>

force-app/main/default/objects/Document_Library__c/Document_Library__c.object-meta.xml
<CustomObject>
    <label>Document Library</label>
    <nameField>
        <label>Document Library Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Library</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Library__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Document Library</relationshipLabel>
    <relationshipName>Document_Library</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Document_Library__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Drivers License Front</fullName>
                <default>true</default>
                <label>Drivers License Front</label>
            </value>
            <value>
                <fullName>Drivers License Back</fullName>
            </value>
            <value>
                <fullName>Payslip One</fullName>
            </value>
            <value>
                <fullName>Payslip Two</fullName>
            </value>
            <value>
                <fullName>Bankstatements</fullName>
            </value>
            <value>
                <fullName>Manual Uploaded Bankstatements</fullName>
            </value>
            <value>
                <fullName>Privacy Policy</fullName>
            </value>
            <value>
                <fullName>Credit File</fullName>
            </value>
            <value>
                <fullName>Sales Invoice</fullName>
            </value>
            <value>
                <fullName>Insurance Certificate</fullName>
            </value>
            <value>
                <fullName>Preliminary Assessment</fullName>
            </value>
            <value>
                <fullName>Medicare</fullName>
            </value>
            <value>
                <fullName>Centrelink Income Statements</fullName>
            </value>
            <value>
                <fullName>Most Recent Tax Return</fullName>
            </value>
            <value>
                <fullName>Notice of Assessment</fullName>
            </value>
            <value>
                <fullName>Partner Declared Income</fullName>
            </value>
            <value>
                <fullName>Tenancy Agreement</fullName>
            </value>
            <value>
                <fullName>Rental Ledger</fullName>
            </value>
            <value>
                <fullName>Trust Deed</fullName>
            </value>
            <value>
                <fullName>Child Support Assessment</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Verifier</fullName>
            </value>
            <value>
                <fullName>Most Recent Partner Payslip</fullName>
            </value>
            <value>
                <fullName>Drivers Licence</fullName>
            </value>
            <value>
                <fullName>Payslips</fullName>
            </value>
            <value>
                <fullName>Partners Payslip</fullName>
            </value>
            <value>
                <fullName>Partners Payslip2</fullName>
            </value>
            <value>
                <fullName>Partners N O A</fullName>
            </value>
            <value>
                <fullName>Partners T R</fullName>
            </value>
            <value>
                <fullName>Partners N O A2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Library__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/s3downloadfileapexTest.cls
@isTest
public class s3downloadfileapexTest {
    
    static testMethod void fileDownload() {
        
        Account a = new account();
        a.name = 'Test';
        insert a;       
        
        Contact c = new contact();
        c.lastname='Test';
        insert c;
        
        Case objcase = new Case();
        objcase.Status = 'Received';
        objcase.Origin = 'Phone';
        //objcase.Contact.Id = c.Id;
        insert objcase;
        
        Document_Library__c resume = new Document_Library__c();
        resume.File_Name__c = 'xyz\\.abc';
        resume.File_Type__c = 'image/jpeg';
        resume.Case__c = objcase.id;
        resume.Document_Type__c = 'Payslip One';   
        resume.Is_Deleted__c = true;
        resume.Expiration_Date__c = date.today().addDays(10);
        insert resume; 
        
        AmazonS3__c setting = new AmazonS3__c();
        setting.name='AmazonS3Credentials';
        setting.AmazonS3_Key__c = 'AKIAZQJDJDSPGNH35IWW';
        setting.AmazonS3_Secret__c = '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';
        setting.AmazonS3_BucketName__c = 'resonanttest2021';
        setting.AmazonS3_Host__c = 's3-us-west-2.amazonaws.com';
        insert setting;
        
        PageReference pageRef = Page.S3downloadfile; // Add your VF page Name here
        pageRef.getParameters().put('id', String.valueOf(resume.Id));
        Test.setCurrentPage(pageRef);
        
        S3downloadfileapex obj = new S3downloadfileapex();
        obj.manageFile();
        obj.generateURL();
        //obj.backToRelatedListView();        
    }
    
}