force-app/main/default/objects/Note__c/Note__c.object-meta.xml
<CustomObject>
    <label>Note</label>
    <nameField>
        <displayFormat>N-{00000000}</displayFormat>
        <label>Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Note</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Note__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Public__c.field-meta.xml
<CustomField>
    <fullName>Public__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SyncNoteToDrivaDBTest.cls
@isTest
public class SyncNoteToDrivaDBTest {
	@isTest 
    public static void testMethod1() {
        
        Note__c nt = new Note__c();
        nt.Public__c = true;
        nt.Content__c = 'test';
        
        // Perform test
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        EntryURL.isFromBrowser = true;
        Database.SaveResult result = Database.insert(nt, false);
        EntryURL.isFromBrowser = false;
        Database.SaveResult result2 = Database.insert(nt, false);
        
        Test.stopTest();
        
        System.assert(result.isSuccess());
        System.assert(!result2.isSuccess());
    }
}